spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081


#Application Configuration
#server:
#  port: 8080
#  error:
#    include-message: always
#    include-binding-errors: always
#    
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    instance:
#      instance-id: ${spring.application.name}:${spring.application.instance_id:${ramdon.value}}
#spring:
#  application:
#    name: product-service
#  boot:
#    admin:
#      client:
#        url: http://localhost:8099
#  
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"